defaultBranch: 'main'
branchName: '${issue.number}'
branches:
  - label: '*'
    prefix: issues/
  - label: ğŸš€ feature
    prefix: feature/
  - label: ğŸ›  refactor
    prefix: refactor/
  - label: ğŸ bug
    prefix: bugfix/
autoCloseIssue: true